all:
  hosts:
    server:
      ansible_host: pve.example.com
      ansible_ssh_user: user1

      zpool: pool0                            # ZFS pool

      alert_email: example@outlook.com        # address for receiving disk related alerts (SMART alerts and ZFS scrub events)

      msmtp_email: example-notif@outlook.com  # sender address for email alerts
      msmtp_smtp_server: smtp.office365.com   # sender address SMTP server
      msmtp_smtp_port: 587                    # sender address SMTP server port

      smartd_mon_disks:                       # disks to monitor with SMART tests
        - /dev/sda
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
        - /dev/sde
