all:
  hosts:
    server:
      ansible_host: pve.example.com
      ansible_ssh_user: user1

      zpools:                                 # zpools to scrub
        - pool0
        - pool1

      alert_email: example@outlook.com        # address for receiving disk related alerts (SMART alerts and ZFS scrub events)

      postfix_email: example-notif@outlook.com  # sender address for email alerts
      postfix_smtp_server: smtp.office365.com   # sender address SMTP server
      postfix_smtp_port: 587                    # sender address SMTP server port

      smartd_mon_disks:                       # disks to monitor with SMART tests
        - /dev/sda
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
        - /dev/sde
