---
- hosts: all
  become: yes

  roles:
    - { role: "postfix", tags: "install" }
    - { role: "smartd", tags: "install" }
    - { role: "zfs-auto-snapshot", tags: "install" }
    - { role: "zfs-scrub", tags: "install" }
