---
- hosts: all
  become: yes

  pre_tasks:
    - name: Load playbook config
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - apt
    - postfix
    - smartd
    - zfs-auto-snapshot
    - zfs-scrub
